// This file is a fuzz entrypoint for AFL++, using shared memory and persistent
// mode instrumentation. It can also be run without AFL++ instrumentation, in
// which it receives input via stdin.

#include "xxutf.h"
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unicode/ucnv.h>
#include <unicode/unorm.h>
#include <unicode/ustring.h>
#include <unicode/utypes.h>
#include <unistd.h>

#if defined(__clang__)
#pragma clang optimize off
#elif defined(__GNUC__)
#pragma GCC optimize("O0")
#endif

// Generated by Claude
static bool is_valid_utf8(const uint8_t *data, size_t len, size_t *pos) {
  size_t i = 0;
  while (i < len) {
    uint8_t byte = data[i];
    size_t remaining = len - i;
    *pos = i;

    if (byte <= 0x7F) {
      // ASCII
      i += 1;
    } else if ((byte & 0xE0) == 0xC0) {
      // 2-byte sequence
      if (remaining < 2 || (data[i + 1] & 0xC0) != 0x80 || byte < 0xC2)
        return false;
      i += 2;
    } else if ((byte & 0xF0) == 0xE0) {
      // 3-byte sequence
      if (remaining < 3)
        return false;
      uint8_t b1 = data[i + 1], b2 = data[i + 2];
      if ((b1 & 0xC0) != 0x80 || (b2 & 0xC0) != 0x80)
        return false;
      if (byte == 0xE0 && b1 < 0xA0)
        return false; // Overlong encoding
      if (byte == 0xED && b1 >= 0xA0)
        return false; // Surrogates
      i += 3;
    } else if ((byte & 0xF8) == 0xF0) {
      // 4-byte sequence
      if (remaining < 4)
        return false;
      uint8_t b1 = data[i + 1], b2 = data[i + 2], b3 = data[i + 3];
      if ((b1 & 0xC0) != 0x80 || (b2 & 0xC0) != 0x80 || (b3 & 0xC0) != 0x80)
        return false;
      if (byte == 0xF0 && b1 < 0x90)
        return false; // Overlong
      if (byte == 0xF4 && b1 > 0x8F)
        return false; // > U+10FFFF
      if (byte > 0xF4)
        return false;
      i += 4;
    } else {
      return false;
    }
  }

  return true;
}

static uint16_t read_uint16le(const uint8_t *buffer) {
  return (uint16_t)buffer[0] | (uint16_t)buffer[1] << 8;
}

static uint16_t read_uint16be(const uint8_t *buffer) {
  return ((uint16_t)buffer[0] << 8) | (uint16_t)buffer[1];
}

#define UTF16_HELPERS(endianness)                                              \
  /* Generated by Claude */                                                    \
  static bool is_valid_utf16##endianness(const uint8_t *buffer, size_t len,    \
                                         size_t *pos) {                        \
                                                                               \
    /* Length must be even (UTF-16 uses 2-byte code units) */                  \
    if (len % 2 != 0) {                                                        \
      if (pos)                                                                 \
        *pos = len - 1;                                                        \
      return false;                                                            \
    }                                                                          \
                                                                               \
    size_t i = 0;                                                              \
    while (i < len) {                                                          \
      /* Read code unit */                                                     \
      uint16_t cu = read_uint16##endianness(buffer + i);                       \
      if (cu >= 0xD800 && cu <= 0xDBFF) {                                      \
        /* High surrogate - must be followed by low surrogate */               \
        if (i + 2 >= len) {                                                    \
          /* No room for low surrogate */                                      \
          if (pos)                                                             \
            *pos = i;                                                          \
          return false;                                                        \
        }                                                                      \
        uint16_t cu2 = read_uint16##endianness(buffer + i + 2);                \
        if (cu2 < 0xDC00 || cu2 > 0xDFFF) {                                    \
          /* Not a valid low surrogate */                                      \
          if (pos)                                                             \
            *pos = i;                                                          \
          return false;                                                        \
        }                                                                      \
        /* Valid surrogate pair, consume both code units */                    \
        i += 4;                                                                \
      } else if (cu >= 0xDC00 && cu <= 0xDFFF) {                               \
        /* Lone low surrogate (not preceded by high surrogate) */              \
        if (pos)                                                               \
          *pos = i;                                                            \
        return false;                                                          \
      } else {                                                                 \
        /* Regular BMP character */                                            \
        i += 2;                                                                \
      }                                                                        \
    }                                                                          \
                                                                               \
    if (pos)                                                                   \
      *pos = i;                                                                \
    return true;                                                               \
  }                                                                            \
                                                                               \
  /* Generated by Claude */                                                    \
  static void print_code_points_utf16##endianness(const char *s, size_t len) { \
    if (s == NULL) {                                                           \
      return;                                                                  \
    }                                                                          \
                                                                               \
    size_t i = 0;                                                              \
    while (i + 1 < len) {                                                      \
      /* Read 16-bit code unit */                                              \
      uint16_t cu = read_uint16##endianness((const uint8_t *)s + i);           \
      i += 2;                                                                  \
                                                                               \
      uint32_t code_point;                                                     \
                                                                               \
      /* Check if this is a high surrogate (0xD800-0xDBFF) */                  \
      if (cu >= 0xD800 && cu <= 0xDBFF) {                                      \
        /* Need a low surrogate to follow */                                   \
        if (i + 1 >= len) {                                                    \
          printf("FFFD "); /* Incomplete surrogate pair */                     \
          break;                                                               \
        }                                                                      \
                                                                               \
        uint16_t cu2 = read_uint16##endianness((const uint8_t *)s + i);        \
        i += 2;                                                                \
                                                                               \
        /* Check if it's a valid low surrogate (0xDC00-0xDFFF) */              \
        if (cu2 >= 0xDC00 && cu2 <= 0xDFFF) {                                  \
          /* Decode surrogate pair */                                          \
          code_point = 0x10000 + ((cu - 0xD800) << 10) + (cu2 - 0xDC00);       \
        } else {                                                               \
          /* Invalid surrogate pair */                                         \
          printf("FFFD ");                                                     \
          i -= 2; /* Back up to reprocess cu2 */                               \
          continue;                                                            \
        }                                                                      \
      } else if (cu >= 0xDC00 && cu <= 0xDFFF) {                               \
        /* Lone low surrogate - invalid */                                     \
        printf("FFFD ");                                                       \
        continue;                                                              \
      } else {                                                                 \
        /* Regular BMP character */                                            \
        code_point = cu;                                                       \
      }                                                                        \
                                                                               \
      printf("%04X ", code_point);                                             \
    }                                                                          \
  }

UTF16_HELPERS(le);
UTF16_HELPERS(be);

#undef UTF16_HELPERS

static bool equal(const char *a, const char *b) {
  for (size_t i = 0;; i++) {
    if (a[i] == '\0') {
      return b[i] == '\0';
    }
    if (a[i] != b[i]) {
      return false;
    }
  }

  return true;
}

// Generated by Claude
static void print_code_points_utf8(const char *s, size_t len) {
  if (!s)
    return;

  size_t i = 0;
  while (i < len) {
    uint32_t code_point;
    unsigned char byte = (unsigned char)s[i];

    if ((byte & 0x80) == 0) {
      code_point = byte;
      i += 1;
    } else if ((byte & 0xE0) == 0xC0) {
      code_point = ((byte & 0x1F) << 6) | (s[i + 1] & 0x3F);
      i += 2;
    } else if ((byte & 0xF0) == 0xE0) {
      code_point =
          ((byte & 0x0F) << 12) | ((s[i + 1] & 0x3F) << 6) | (s[i + 2] & 0x3F);
      i += 3;
    } else {
      code_point = ((byte & 0x07) << 18) | ((s[i + 1] & 0x3F) << 12) |
                   ((s[i + 2] & 0x3F) << 6) | (s[i + 3] & 0x3F);
      i += 4;
    }

    printf("%04X ", code_point);
  }
}

#define COMPARE_NORMALIZE_FUNCTION_UTF8(form, form_upper)                      \
  static bool compare_normalization_utf8_##form(const char *input,             \
                                                size_t length, bool verbose) { \
    UErrorCode status = U_ZERO_ERROR;                                          \
    UChar source[8192];                                                        \
    int32_t source_length;                                                     \
    u_strFromUTF8(source, 8192, &source_length, input, length, &status);       \
    if (U_FAILURE(status)) {                                                   \
      printf("error converting to UTF-16: %s\n", u_errorName(status));         \
      return false;                                                            \
    }                                                                          \
                                                                               \
    const UNormalizer2 *normalizer =                                           \
        unorm2_get##form_upper##Instance(&status);                             \
    if (U_FAILURE(status)) {                                                   \
      printf("error getting normalizer: %s\n", u_errorName(status));           \
      return false;                                                            \
    }                                                                          \
                                                                               \
    UChar result[8192];                                                        \
    int32_t result_length = unorm2_normalize(                                  \
        normalizer, source, source_length, result, 8192, &status);             \
    if (U_FAILURE(status)) {                                                   \
      printf("error normalizing: %s\n", u_errorName(status));                  \
      return false;                                                            \
    }                                                                          \
                                                                               \
    char icu_out[8192];                                                        \
    int32_t icu_out_length;                                                    \
    u_strToUTF8(icu_out, 8192, &icu_out_length, result, result_length,         \
                &status);                                                      \
    if (U_FAILURE(status)) {                                                   \
      printf("error converting to UTF-8: %s\n", u_errorName(status));          \
      return false;                                                            \
    }                                                                          \
                                                                               \
    char xxutf_out[8192];                                                      \
    size_t xxutf_out_length =                                                  \
        xxutf_normalize_utf8_##form(input, length, xxutf_out);                 \
    size_t pos;                                                                \
    if (!is_valid_utf8((const uint8_t *)xxutf_out, xxutf_out_length, &pos)) {  \
      if (verbose) {                                                           \
        printf("normalized (%s) output is invaild UTF-8, position %zu\n",      \
               #form_upper, pos);                                              \
      }                                                                        \
      return false;                                                            \
    }                                                                          \
                                                                               \
    icu_out[icu_out_length] = '\0';                                            \
    xxutf_out[xxutf_out_length] = '\0';                                        \
                                                                               \
    if (!equal(xxutf_out, icu_out)) {                                          \
      if (verbose) {                                                           \
        printf("Buffers (UTF-8, %s) not equal\n", #form_upper);                \
        printf("   input: ");                                                  \
        print_code_points_utf8(input, length);                                 \
        printf("\n");                                                          \
        printf("xxutf: ");                                                     \
        print_code_points_utf8(xxutf_out, xxutf_out_length);                   \
        printf("\n");                                                          \
        printf("   icu4c: ");                                                  \
        print_code_points_utf8(icu_out, icu_out_length);                       \
        printf("\n");                                                          \
      }                                                                        \
      return false;                                                            \
    }                                                                          \
    if (verbose) {                                                             \
      printf("Both buffers (UTF-8, %s) equal!\n", #form_upper);                \
    }                                                                          \
    return true;                                                               \
  }

COMPARE_NORMALIZE_FUNCTION_UTF8(nfd, NFD);
COMPARE_NORMALIZE_FUNCTION_UTF8(nfc, NFC);
COMPARE_NORMALIZE_FUNCTION_UTF8(nfkd, NFKD);
COMPARE_NORMALIZE_FUNCTION_UTF8(nfkc, NFKC);

#undef COMPARE_NORMALIZE_FUNCTION_UTF8

#define COMPARE_NORMALIZE_FUNCTION_UTF16(form, form_upper, endianness,         \
                                         endianness_upper)                     \
  static bool compare_normalization_utf16##endianness##_##form(                \
      const char *input, size_t length, bool verbose) {                        \
    UErrorCode status = U_ZERO_ERROR;                                          \
    UChar source[8192];                                                        \
    int32_t source_length;                                                     \
    u_strFromUTF8(source, 8192, &source_length, input, length, &status);       \
    if (U_FAILURE(status)) {                                                   \
      printf("error converting to UTF-16: %s\n", u_errorName(status));         \
      return false;                                                            \
    }                                                                          \
                                                                               \
    const UNormalizer2 *normalizer =                                           \
        unorm2_get##form_upper##Instance(&status);                             \
    if (U_FAILURE(status)) {                                                   \
      printf("error getting normalizer: %s\n", u_errorName(status));           \
      return false;                                                            \
    }                                                                          \
                                                                               \
    UChar result[8192];                                                        \
    int32_t result_length = unorm2_normalize(                                  \
        normalizer, source, source_length, result, 8192, &status);             \
    if (U_FAILURE(status)) {                                                   \
      printf("error normalizing: %s\n", u_errorName(status));                  \
      return false;                                                            \
    }                                                                          \
                                                                               \
    UConverter *conv = ucnv_open("UTF-16" #endianness_upper, &status);         \
    if (U_FAILURE(status)) {                                                   \
      printf("error opening UTF-16 converter: %s\n", u_errorName(status));     \
      return false;                                                            \
    }                                                                          \
                                                                               \
    int32_t icu_out_length =                                                   \
        ucnv_fromUChars(conv, NULL, 0, result, result_length, &status);        \
    if (status != U_BUFFER_OVERFLOW_ERROR && U_FAILURE(status)) {              \
      printf("error calculating size: %s\n", u_errorName(status));             \
      ucnv_close(conv);                                                        \
      return 1;                                                                \
    }                                                                          \
    status = U_ZERO_ERROR;                                                     \
                                                                               \
    char icu_out[8192];                                                        \
    ucnv_fromUChars(conv, icu_out, 8192, result, result_length, &status);      \
    if (U_FAILURE(status)) {                                                   \
      printf("error converting to UTF-16: %s\n", u_errorName(status));         \
      ucnv_close(conv);                                                        \
      return false;                                                            \
    }                                                                          \
                                                                               \
    char utf16_bytes[8192];                                                    \
    int32_t utf16_length = ucnv_fromUChars(conv, utf16_bytes, 8192, source,    \
                                           source_length, &status);            \
    if (U_FAILURE(status)) {                                                   \
      printf("error converting to UTF-16: %s\n", u_errorName(status));         \
      ucnv_close(conv);                                                        \
      return false;                                                            \
    }                                                                          \
                                                                               \
    char xxutf_out[8192];                                                      \
    size_t xxutf_out_length = xxutf_normalize_utf16##endianness##_##form(      \
        utf16_bytes, utf16_length, xxutf_out);                                 \
    size_t pos;                                                                \
    if (!is_valid_utf16##endianness((const uint8_t *)xxutf_out,                \
                                    xxutf_out_length, &pos)) {                 \
      if (verbose) {                                                           \
        printf("normalized (%s, %s) output is invaild UTF-16, position %zu\n", \
               "UTF-16" #endianness_upper, #form_upper, pos);                  \
      }                                                                        \
      return false;                                                            \
    }                                                                          \
                                                                               \
    icu_out[icu_out_length] = '\0';                                            \
    xxutf_out[xxutf_out_length] = '\0';                                        \
                                                                               \
    if (!equal(xxutf_out, icu_out)) {                                          \
      if (verbose) {                                                           \
        printf("Buffers (%s, %s) not equal\n", "UTF-16" #endianness_upper,     \
               #form_upper);                                                   \
        printf("   input: ");                                                  \
        print_code_points_utf8(input, length);                                 \
        printf("\n");                                                          \
        printf("xxutf: ");                                                     \
        print_code_points_utf16##endianness(xxutf_out, xxutf_out_length);      \
        printf("\n");                                                          \
        printf("   icu4c: ");                                                  \
        print_code_points_utf16##endianness(icu_out, icu_out_length);          \
        printf("\n");                                                          \
      }                                                                        \
      ucnv_close(conv);                                                        \
      return false;                                                            \
    }                                                                          \
    if (verbose) {                                                             \
      printf("Both buffers (%s, %s) equal!\n", "UTF-16" #endianness_upper,     \
             #form_upper);                                                     \
    }                                                                          \
    ucnv_close(conv);                                                          \
    return true;                                                               \
  }

COMPARE_NORMALIZE_FUNCTION_UTF16(nfd, NFD, le, LE);
COMPARE_NORMALIZE_FUNCTION_UTF16(nfd, NFD, be, BE);
COMPARE_NORMALIZE_FUNCTION_UTF16(nfkd, NFKD, le, LE);
COMPARE_NORMALIZE_FUNCTION_UTF16(nfkd, NFKD, be, BE);
COMPARE_NORMALIZE_FUNCTION_UTF16(nfc, NFC, le, LE);
COMPARE_NORMALIZE_FUNCTION_UTF16(nfc, NFC, be, BE);
COMPARE_NORMALIZE_FUNCTION_UTF16(nfkc, NFKC, le, LE);
COMPARE_NORMALIZE_FUNCTION_UTF16(nfkc, NFKC, be, BE);

#undef COMPARE_NORMALIZE_FUNCTION_UTF16

#ifdef __AFL_FUZZ_TESTCASE_LEN
__AFL_FUZZ_INIT();
#endif

int main() {
#ifdef __AFL_FUZZ_TESTCASE_LEN
  unsigned char *buf = __AFL_FUZZ_TESTCASE_BUF;

  const char *normalization_form = getenv("XXUTF_FUZZ_NORMALIZATION_FORM");
  const char *encoding = getenv("XXUTF_FUZZ_ENCODING");
  if (normalization_form == NULL) {
    normalization_form = "NFD";
  }
  if (encoding == NULL) {
    encoding = "UTF-8";
  }

  bool (*compare_func)(const char *, size_t, bool);

  if (strcmp(encoding, "UTF-8") == 0) {
    if (strcmp(normalization_form, "NFD") == 0) {
      compare_func = compare_normalization_utf8_nfd;
    } else if (strcmp(normalization_form, "NFC") == 0) {
      compare_func = compare_normalization_utf8_nfc;
    } else if (strcmp(normalization_form, "NFKD") == 0) {
      compare_func = compare_normalization_utf8_nfkd;
    } else if (strcmp(normalization_form, "NFKC") == 0) {
      compare_func = compare_normalization_utf8_nfkc;
    } else {
      printf("Invalid normalization form: %s\n", normalization_form);
      abort();
    }
  } else if (strcmp(encoding, "UTF-16LE") == 0) {
    if (strcmp(normalization_form, "NFD") == 0) {
      compare_func = compare_normalization_utf16le_nfd;
    } else if (strcmp(normalization_form, "NFKD") == 0) {
      compare_func = compare_normalization_utf16le_nfkd;
    } else if (strcmp(normalization_form, "NFC") == 0) {
      compare_func = compare_normalization_utf16le_nfc;
    } else if (strcmp(normalization_form, "NFKC") == 0) {
      compare_func = compare_normalization_utf16le_nfkc;
    } else {
      printf("Invalid normalization form: %s\n", normalization_form);
      abort();
    }
  } else if (strcmp(encoding, "UTF-16BE") == 0) {
    if (strcmp(normalization_form, "NFD") == 0) {
      compare_func = compare_normalization_utf16be_nfd;
    } else if (strcmp(normalization_form, "NFKD") == 0) {
      compare_func = compare_normalization_utf16be_nfkd;
    } else if (strcmp(normalization_form, "NFC") == 0) {
      compare_func = compare_normalization_utf16be_nfc;
    } else if (strcmp(normalization_form, "NFKC") == 0) {
      compare_func = compare_normalization_utf16be_nfkc;
    } else {
      printf("Invalid normalization form: %s\n", normalization_form);
      abort();
    }
  } else {
    printf("Invalid encoding form: %s\n", encoding);
    abort();
  }

  while (__AFL_LOOP(1000)) {
    int len = __AFL_FUZZ_TESTCASE_LEN;

    // Ensure valid input
    size_t pos;
    if (!is_valid_utf8(buf, len, &pos) || len > 2048) {
      continue;
    }

    if (!compare_func((const char *)buf, len, false)) {
      abort();
    }

    return 0;
  }
#else
  char buf[4096];
  ssize_t nread;

  while ((nread = read(0, buf, sizeof(buf) - 1)) > 0) {
    buf[nread] = '\0';

    size_t pos;
    if (!is_valid_utf8(buf, nread, &pos)) {
      printf("invalid UTF-8 inputted at position %u\n", pos);
      continue;
    }

    if (!compare_normalization_utf8_nfd(buf, nread, true)) {
      continue;
    }
    if (!compare_normalization_utf8_nfc(buf, nread, true)) {
      continue;
    }
    if (!compare_normalization_utf8_nfkd(buf, nread, true)) {
      continue;
    }
    if (!compare_normalization_utf8_nfkc(buf, nread, true)) {
      continue;
    }
    if (!compare_normalization_utf16le_nfd(buf, nread, true)) {
      continue;
    }
    if (!compare_normalization_utf16be_nfd(buf, nread, true)) {
      continue;
    }
    if (!compare_normalization_utf16le_nfkd(buf, nread, true)) {
      continue;
    }
    if (!compare_normalization_utf16be_nfkd(buf, nread, true)) {
      continue;
    }
    if (!compare_normalization_utf16le_nfc(buf, nread, true)) {
      continue;
    }
    if (!compare_normalization_utf16be_nfc(buf, nread, true)) {
      continue;
    }
    if (!compare_normalization_utf16le_nfkc(buf, nread, true)) {
      continue;
    }
    if (!compare_normalization_utf16be_nfkc(buf, nread, true)) {
      continue;
    }
  }

  return 0;
#endif
}
