// This file was generated by gen/gen.py

#ifndef XXUTF_NORMDATA_H
#define XXUTF_NORMDATA_H

#include <stdint.h>

typedef struct NormdataTableEntry {
  uint8_t len;
  uint8_t ccc;
  uint8_t last_ccc;
  uint16_t offset;
  uint32_t k;
} NormdataTableEntry;

typedef struct NormdataHangulShuf {
  uint8_t len;
  uint8_t tbl[24];
} NormdataHangulShuf;

static const uint16_t NORMDATA_S_BASE = 0xAC00;
static const uint16_t NORMDATA_L_BASE = 0x1100;
static const uint16_t NORMDATA_V_BASE = 0x1161;
static const uint16_t NORMDATA_T_BASE = 0x11A7;
static const uint16_t NORMDATA_L_COUNT = 19;
static const uint16_t NORMDATA_V_COUNT = 21;
static const uint16_t NORMDATA_T_COUNT = 28;
static const uint16_t NORMDATA_N_COUNT = NORMDATA_V_COUNT * NORMDATA_T_COUNT;
static const uint16_t NORMDATA_S_COUNT = NORMDATA_L_COUNT * NORMDATA_N_COUNT;

uint32_t normdata_compose_supplementary(uint32_t c1, uint32_t c2);

extern const uint32_t NORMDATA_NFD_CHARS[873];
extern const uint16_t NORMDATA_NFD_SALT[814];
extern const NormdataTableEntry NORMDATA_NFD_KV[814];
extern const uint32_t NORMDATA_NFKD_CHARS[2409];
extern const uint16_t NORMDATA_NFKD_SALT[2251];
extern const NormdataTableEntry NORMDATA_NFKD_KV[2251];
extern const uint16_t NORMDATA_NFC_SALT[928];
extern const uint32_t NORMDATA_NFC_KV[928][2];
extern const uint16_t NORMDATA_CASEFOLD_SALT[282];
extern const uint32_t NORMDATA_CASEFOLD_KV[282][2];
extern const uint8_t NORMDATA_SHUFUTF8[145][16];
extern const uint8_t NORMDATA_CODE_POINT_INDEX[4096][2];
extern const uint8_t NORMDATA_SHUFUTF8_INDEX_12;
extern const uint8_t NORMDATA_SHUFUTF8_INDEX_123;
extern const uint8_t NORMDATA_SHUFUTF8_INDEX_1234;
extern const NormdataHangulShuf NORMDATA_HANGUL_SHUF[16];
extern const uint8_t NORMDATA_UTF8_NFD_TRIE_DECOMPOSITIONS[7753];
extern const uint8_t NORMDATA_UTF8_NFKD_TRIE_DECOMPOSITIONS[16025];
extern const uint16_t NORMDATA_UTF8_NFD_TRIE_INDEX[1024];
extern const uint32_t NORMDATA_UTF8_NFD_TRIE_DATA[6436];
extern const uint16_t NORMDATA_UTF8_NFKD_TRIE_INDEX[1024];
extern const uint32_t NORMDATA_UTF8_NFKD_TRIE_DATA[9690];
extern const uint8_t NORMDATA_UTF16_NFD_TRIE_DECOMPOSITIONS[7028];
extern const uint8_t NORMDATA_UTF16_NFKD_TRIE_DECOMPOSITIONS[15440];
extern const uint16_t NORMDATA_UTF16_NFD_TRIE_INDEX[1024];
extern const uint32_t NORMDATA_UTF16_NFD_TRIE_DATA[6436];
extern const uint16_t NORMDATA_UTF16_NFKD_TRIE_INDEX[1024];
extern const uint32_t NORMDATA_UTF16_NFKD_TRIE_DATA[9690];
extern const uint16_t NORMDATA_CCC_TRIE_INDEX[1024];
extern const uint8_t NORMDATA_CCC_TRIE_DATA[3319];
extern const uint32_t NORMDATA_NFC_BLOOM_FILTER[4096];
extern const uint32_t NORMDATA_NFKC_BLOOM_FILTER[4096];
extern const uint32_t NORMDATA_NON_STARTERS_BLOOM_FILTER[4096];
extern const uint8_t NORMDATA_UTF8_CASEFOLD_DATA[471];
extern const uint16_t NORMDATA_UTF8_CASEFOLD_TRIE_INDEX[1024];
extern const uint32_t NORMDATA_UTF8_CASEFOLD_TRIE_DATA[2549];

static const uint32_t NORMDATA_NFD_TABLE_SIZE = sizeof(NORMDATA_NFD_KV) / sizeof(NormdataTableEntry);
static const uint32_t NORMDATA_NFKD_TABLE_SIZE = sizeof(NORMDATA_NFKD_KV) / sizeof(NormdataTableEntry);
static const uint32_t NORMDATA_NFC_TABLE_SIZE = sizeof(NORMDATA_NFC_KV) / sizeof(uint64_t);
static const uint32_t NORMDATA_CASEFOLD_TABLE_SIZE = sizeof(NORMDATA_CASEFOLD_KV) / sizeof(uint64_t);

static const uint8_t NORMDATA_UTF8_SIZE[256] = {
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
    4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0};

#endif // XXUTF_NORMDATA_H
