// This file was generated by gen/gen.py

#ifndef UTF8NORM_NORMDATA_H
#define UTF8NORM_NORMDATA_H

#include <stdint.h>

typedef struct NormdataEntry {
  uint8_t len;
  uint8_t ccc;
  uint16_t offset;
  uint32_t k;
} NormdataEntry;

typedef struct NormdataHangulShuf {
  uint8_t len;
  uint8_t tbl[24];
} NormdataHangulShuf;

static const uint16_t NORMDATA_S_BASE = 0xAC00;
static const uint16_t NORMDATA_L_BASE = 0x1100;
static const uint16_t NORMDATA_V_BASE = 0x1161;
static const uint16_t NORMDATA_T_BASE = 0x11A7;
static const uint16_t NORMDATA_L_COUNT = 19;
static const uint16_t NORMDATA_V_COUNT = 21;
static const uint16_t NORMDATA_T_COUNT = 28;
static const uint16_t NORMDATA_N_COUNT = NORMDATA_V_COUNT * NORMDATA_T_COUNT;
static const uint16_t NORMDATA_S_COUNT = NORMDATA_L_COUNT * NORMDATA_N_COUNT;

extern const uint8_t NORMDATA_DECOMPOSED_CHARS[10804];
extern const uint16_t NORMDATA_DECOMPOSED_SALT[3011];
extern const NormdataEntry NORMDATA_DECOMPOSED_KV[3011];
extern const uint8_t NORMDATA_SHUFUTF8[145][16];
extern const uint8_t NORMDATA_CODEPOINT_INDEX[4096][2];
extern const uint8_t NORMDATA_SHUFUTF8_INDEX_12;
extern const uint8_t NORMDATA_SHUFUTF8_INDEX_123;
extern const uint8_t NORMDATA_SHUFUTF8_INDEX_1234;
extern const NormdataHangulShuf NORMDATA_HANGUL_SHUF[16];
extern const uint32_t NORMDATA_BLOOM_FILTER[4096];

static const uint32_t NORMDATA_DECOMPOSED_TABLE_SIZE = sizeof(NORMDATA_DECOMPOSED_KV) / 2;

#endif // UTF8NORM_NORMDATA_H
