// This file was generated by gen/gen.py

#ifndef XXUTF_UNIDATA_H
#define XXUTF_UNIDATA_H

#include <stdint.h>

typedef struct UnidataTableEntry {
  uint8_t len;
  uint8_t ccc;
  uint8_t last_ccc;
  uint16_t offset;
  uint32_t k;
} UnidataTableEntry;

typedef struct UnidataHangulShuf {
  uint8_t len;
  uint8_t tbl[24];
} UnidataHangulShuf;

static const uint16_t UNIDATA_S_BASE = 0xAC00;
static const uint16_t UNIDATA_L_BASE = 0x1100;
static const uint16_t UNIDATA_V_BASE = 0x1161;
static const uint16_t UNIDATA_T_BASE = 0x11A7;
static const uint16_t UNIDATA_L_COUNT = 19;
static const uint16_t UNIDATA_V_COUNT = 21;
static const uint16_t UNIDATA_T_COUNT = 28;
static const uint16_t UNIDATA_N_COUNT = UNIDATA_V_COUNT * UNIDATA_T_COUNT;
static const uint16_t UNIDATA_S_COUNT = UNIDATA_L_COUNT * UNIDATA_N_COUNT;

uint32_t unidata_compose_supplementary(uint32_t c1, uint32_t c2);

extern const uint32_t UNIDATA_NFD_CHARS[873];
extern const uint16_t UNIDATA_NFD_SALT[814];
extern const UnidataTableEntry UNIDATA_NFD_KV[814];
extern const uint32_t UNIDATA_NFKD_CHARS[2409];
extern const uint16_t UNIDATA_NFKD_SALT[2251];
extern const UnidataTableEntry UNIDATA_NFKD_KV[2251];
extern const uint16_t UNIDATA_NFC_SALT[928];
extern const uint32_t UNIDATA_NFC_KV[928][2];
extern const uint16_t UNIDATA_CASEFOLD_SALT[282];
extern const uint32_t UNIDATA_CASEFOLD_KV[282][2];
extern const uint8_t UNIDATA_SHUFUTF8[145][16];
extern const uint8_t UNIDATA_CODE_POINT_INDEX[4096][2];
extern const uint8_t UNIDATA_SHUFUTF8_INDEX_12_SMALL;
extern const uint8_t UNIDATA_SHUFUTF8_INDEX_12;
extern const uint8_t UNIDATA_SHUFUTF8_INDEX_123;
extern const uint8_t UNIDATA_SHUFUTF8_INDEX_1234;
extern const uint8_t UNIDATA_SHUFUTF8_WIDE[209][16];
extern const uint8_t UNIDATA_CODE_POINT_INDEX_WIDE[4096][2];
extern const uint8_t UNIDATA_SHUFUTF8_WIDE_INDEX_12_SMALL;
extern const uint8_t UNIDATA_SHUFUTF8_WIDE_INDEX_12;
extern const uint8_t UNIDATA_SHUFUTF8_WIDE_INDEX_123;
extern const uint8_t UNIDATA_SHUFUTF8_WIDE_INDEX_1234;
extern const UnidataHangulShuf UNIDATA_HANGUL_SHUF[16];
extern const uint8_t UNIDATA_UTF16_DECOMP_SHUF[256][16];
extern const uint8_t UNIDATA_UTF8_NFD_TRIE_DECOMPOSITIONS[7754];
extern const uint8_t UNIDATA_UTF8_NFKD_TRIE_DECOMPOSITIONS[16026];
extern const uint16_t UNIDATA_UTF8_NFD_TRIE_INDEX[1024];
extern const uint16_t UNIDATA_UTF8_NFD_TRIE_DATA[6000];
extern const uint16_t UNIDATA_UTF8_NFD_DATA_TRIE_INDEX[1024];
extern const uint32_t UNIDATA_UTF8_NFD_DATA_TRIE_DATA[6436];
extern const uint16_t UNIDATA_UTF8_NFKD_TRIE_INDEX[1024];
extern const uint16_t UNIDATA_UTF8_NFKD_TRIE_DATA[8724];
extern const uint16_t UNIDATA_UTF8_NFKD_DATA_TRIE_INDEX[1024];
extern const uint32_t UNIDATA_UTF8_NFKD_DATA_TRIE_DATA[9690];
extern const uint8_t UNIDATA_UTF16_NFD_TRIE_DECOMPOSITIONS[7029];
extern const uint8_t UNIDATA_UTF16_NFKD_TRIE_DECOMPOSITIONS[15441];
extern const uint16_t UNIDATA_UTF16_NFD_TRIE_INDEX[1024];
extern const uint32_t UNIDATA_UTF16_NFD_TRIE_DATA[6436];
extern const uint16_t UNIDATA_UTF16_NFKD_TRIE_INDEX[1024];
extern const uint32_t UNIDATA_UTF16_NFKD_TRIE_DATA[9690];
extern const uint16_t UNIDATA_CCC_TRIE_INDEX[1024];
extern const uint8_t UNIDATA_CCC_TRIE_DATA[3319];
extern const uint16_t UNIDATA_NFC_TRIE_INDEX[1024];
extern const uint8_t UNIDATA_NFC_TRIE_DATA[4347];
extern const uint16_t UNIDATA_NFKC_TRIE_INDEX[1024];
extern const uint8_t UNIDATA_NFKC_TRIE_DATA[7140];
extern const uint32_t UNIDATA_NFC_BLOOM_FILTER[1024];
extern const uint32_t UNIDATA_NFKC_BLOOM_FILTER[1024];
extern const uint32_t UNIDATA_NON_STARTERS_BLOOM_FILTER[1024];
extern const uint8_t UNIDATA_UTF8_CASEFOLD_DATA[3447];
extern const uint16_t UNIDATA_UTF8_CASEFOLD_TRIE_INDEX[1024];
extern const uint16_t UNIDATA_UTF8_CASEFOLD_TRIE_DATA[2942];
extern const uint8_t UNIDATA_UTF16_CASEFOLD_DATA[2790];
extern const uint16_t UNIDATA_UTF16_CASEFOLD_TRIE_INDEX[1024];
extern const uint16_t UNIDATA_UTF16_CASEFOLD_TRIE_DATA[2942];
extern const uint16_t UNIDATA_UTF8_NFD_LENGTH_TRIE_INDEX[1024];
extern const uint8_t UNIDATA_UTF8_NFD_LENGTH_TRIE_DATA[3268];
extern const uint16_t UNIDATA_UTF8_NFKD_LENGTH_TRIE_INDEX[1024];
extern const uint8_t UNIDATA_UTF8_NFKD_LENGTH_TRIE_DATA[5784];
extern const uint16_t UNIDATA_UTF8_CASEFOLD_LENGTH_TRIE_INDEX[1024];
extern const uint8_t UNIDATA_UTF8_CASEFOLD_LENGTH_TRIE_DATA[996];
extern const uint16_t UNIDATA_UTF16_NFD_LENGTH_TRIE_INDEX[1024];
extern const uint8_t UNIDATA_UTF16_NFD_LENGTH_TRIE_DATA[3140];
extern const uint16_t UNIDATA_UTF16_NFKD_LENGTH_TRIE_INDEX[1024];
extern const uint8_t UNIDATA_UTF16_NFKD_LENGTH_TRIE_DATA[5012];
extern const uint16_t UNIDATA_UTF16_CASEFOLD_LENGTH_TRIE_INDEX[1024];
extern const uint8_t UNIDATA_UTF16_CASEFOLD_LENGTH_TRIE_DATA[539];
extern const uint16_t UNIDATA_UTF8_NFC_LENGTH_TRIE_INDEX[1024];
extern const uint8_t UNIDATA_UTF8_NFC_LENGTH_TRIE_DATA[1032];
extern const uint16_t UNIDATA_UTF8_NFKC_LENGTH_TRIE_INDEX[1024];
extern const uint8_t UNIDATA_UTF8_NFKC_LENGTH_TRIE_DATA[3918];
extern const uint16_t UNIDATA_UTF16_NFC_LENGTH_TRIE_INDEX[1024];
extern const uint8_t UNIDATA_UTF16_NFC_LENGTH_TRIE_DATA[871];
extern const uint16_t UNIDATA_UTF16_NFKC_LENGTH_TRIE_INDEX[1024];
extern const uint8_t UNIDATA_UTF16_NFKC_LENGTH_TRIE_DATA[3245];

static const uint8_t UNIDATA_UTF8_SIZE[256] = {
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
    4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0};

#endif // XXUTF_UNIDATA_H
